name: Check code quality
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Requirements
        run: |
          pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install -r requirements.txt

      - name: Run Flake8
        run: flake8 --max-line-length 119 ./src

      - name: Prepare TestBed
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libopus-dev

      - name: Test Run
        run: |
          python src/main.py &
          sleep 20
          kill "$!"
        env:
          BOT_TOKEN: ${{ secrets.TEST_BOI_DC_TOKEN }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_ENDPOINT: ${{ secrets.SERVER_ENDPOINT }}
          WAVELINK_URL: ${{ secrets.WAVELINK_URL }}
          WAVELINK_PORT: ${{ secrets.WAVELINK_PORT }}
          WAVELINK_PASSWORD: ${{ secrets.WAVELINK_PASSWORD }}