name: Check code quality
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: |
          pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Run PyLint
        run: pylint ./src
