name: Testing Bot Run
on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: Git branch or other ref (required)

jobs:
  docker_build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.git_ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: "ghcr.io/wkk-offcial/boi_redemption_arc:${{ github.event.inputs.git_ref }}"

  deploy:
    name: Deploy to EC2
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Image on EC2
      uses: appleboy/ssh-action@v0.1.8
      env:
        DISCORD_TOKEN: ${{ secrets.BOI_DISCORD_TOKEN }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_ENDPOINT: ${{ secrets.SERVER_ENDPOINT }}
        DOCKER_BOI_IMAGE: "ghcr.io/wkk-offcial/boi_redemption_arc:latest"
        DOCKER_BOI_NAME: "wkk_boi"
        WAVELINK_URL: ${{ secrets.WAVELINK_URL }}
        WAVELINK_PORT: ${{ secrets.WAVELINK_PORT }}
        WAVELINK_PASSWORD: ${{ secrets.WAVELINK_PASSWORD }}
      with:
        host: ${{secrets.BOI_HOSTNAME}}
        username: ec2-user
        key: ${{secrets.BOI_PRIVATE_KEY}}
        envs: DISCORD_TOKEN, SERVER_IP, SERVER_ENDPOINT, SERVER_PORT, DOCKER_BOI_IMAGE, DOCKER_BOI_NAME, WAVELINK_URL, WAVELINK_PORT, WAVELINK_PASSWORD
        script_stop: true
        script: |
          if [[ -z "$(docker network ls | grep wkk-network)" ]]; then
            docker network create wkk-network
          fi
          docker pull $DOCKER_BOI_IMAGE
          docker stop $DOCKER_BOI_NAME && docker rm -fv $DOCKER_BOI_NAME || true
          docker run --restart on-failure \
          --detach \
          --network="wkk-network" \
          -e BOT_TOKEN=$DISCORD_TOKEN \
          -e SERVER_IP=$SERVER_IP \
          -e SERVER_PORT=$SERVER_PORT \
          -e SERVER_ENDPOINT=$SERVER_ENDPOINT \
          -e WAVELINK_URL=$WAVELINK_URL \
          -e WAVELINK_PORT=$WAVELINK_PORT \
          -e WAVELINK_PASSWORD=$WAVELINK_PASSWORD \
          -e SENTRY_KEY=$SENTRY_KEY \
          -v /home/ec2-user/soundboards:/wkk-bot/cache/soundboards \
          --name $DOCKER_BOI_NAME \
          $DOCKER_BOI_IMAGE

          docker image prune <<< y

  destroy:
      name: Stop test Boi
      needs: deploy
      runs-on: ubuntu-latest
      environment: testing
      steps:
      - name: Remove running container from EC2
        uses: appleboy/ssh-action@v0.1.8
        env:
          DOCKER_BOI_TEST_NAME: "test_boi"
        with:
          host: ${{secrets.BOI_HOSTNAME}}
          username: ec2-user
          key: ${{secrets.BOI_PRIVATE_KEY}}
          envs:  DOCKER_BOI_IMAGE_TEST, DOCKER_BOI_TEST_NAME
          script: |
            docker stop $DOCKER_BOI_TEST_NAME && docker rm -fv $DOCKER_BOI_TEST_NAME